export default {
  env: {
    node: true,
    es2022: true,
  },
  plugins: ["typescript", "unicorn", "oxc"],
  jsPlugins: [
    { name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" },
  ],
  ignorePatterns: [
    "dist/**",
    "node_modules/**",
    "esbuild.js",
    ".agents/**",
    ".gemini/**",
    "tools/oxlint/anti-slop/**",
  ],
  rules: {
    "no-unused-vars": "error",
    "no-undef": "error",
    "no-constant-condition": "error",
    "no-debugger": "error",
    "no-empty": "error",
    "no-unreachable": "error",
    "eqeqeq": "error",
    "anti-slop/no-chained-type-assertions": "error",
    "anti-slop/no-conditional-empty-object-spread": "error",
    "anti-slop/no-known-value-widening": "error",
    "anti-slop/no-module-mocking": "error",
    "anti-slop/no-object-parameters": "error",
    "anti-slop/no-reflect-apply": "error",
    "anti-slop/no-reflect-get": "error",
    "anti-slop/no-runtime-typeof": "error",
    "anti-slop/no-shape-in-symbol-names": "error",
    "anti-slop/no-unknown-parameters": "error",
    "anti-slop/no-unknown-returns": "error",
    "anti-slop/no-unknown-type-aliases": "error",
    "anti-slop/no-unsafe-dictionary-type": "error",
    "anti-slop/no-widen-then-assert": "error",
    "anti-slop/require-safety-comment-for-type-assertion": "error",
  },
};
